// Folds src/console (markup, styles, script: three ordinary files) into
// src/gen/console.ts, the strings the relay serves as its page. A generated
// module rather than wrangler's text-module rules, since celld deploy
// refuses a config with "rules" (scripts/check-celld.mjs). `--check`
// rebuilds in memory and fails when the committed file is stale, so
// typecheck catches a forgotten rebuild.
import { readFileSync, writeFileSync } from "node:fs";

const OUT = new URL("../src/gen/console.ts", import.meta.url);
const read = (name) => readFileSync(new URL("../src/console/" + name, import.meta.url), "utf8");
const html = read("console.html");
const css = read("console.css");
const js = read("console.js");
const file = `// Generated by scripts/build-console.mjs from src/console. Do not edit; run npm run build:console.
export const CONSOLE_HTML = ${JSON.stringify(html)};
export const CONSOLE_CSS = ${JSON.stringify(css)};
export const CONSOLE_JS = ${JSON.stringify(js)};
`;
if (process.argv.includes("--check")) {
  let cur = "";
  try {
    cur = readFileSync(OUT, "utf8");
  } catch {
    /* missing */
  }
  if (cur !== file) {
    console.error("src/gen/console.ts is stale: run npm run build:console");
    process.exit(1);
  }
} else {
  writeFileSync(OUT, file);
  console.log(`src/gen/console.ts: ${((html.length + css.length + js.length) / 1024).toFixed(0)} KB`);
}
