// Bundles scripts/signer-entry.js into src/gen/signer.ts, a string the relay
// serves at /signer.js. `--check` rebuilds in memory and fails when the
// committed file is stale, so typecheck catches a forgotten rebuild.
import { buildSync } from "esbuild";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const OUT = new URL("../src/gen/signer.ts", import.meta.url);
const result = buildSync({
  entryPoints: [new URL("./signer-entry.js", import.meta.url).pathname],
  bundle: true,
  minify: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  write: false,
  legalComments: "none",
  logLevel: "silent",
});
const js = result.outputFiles[0].text;
const hash = createHash("sha256").update(js).digest("hex").slice(0, 12);
const file = `// Generated by scripts/build-signer.mjs from scripts/signer-entry.js. Do not edit; run npm run build:signer.
export const SIGNER_HASH = ${JSON.stringify(hash)};
export const SIGNER_JS = ${JSON.stringify(js)};
`;
if (process.argv.includes("--check")) {
  let cur = "";
  try {
    cur = readFileSync(OUT, "utf8");
  } catch {
    /* missing */
  }
  if (cur !== file) {
    console.error("src/gen/signer.ts is stale: run npm run build:signer");
    process.exit(1);
  }
} else {
  writeFileSync(OUT, file);
  console.log(`src/gen/signer.ts: ${(js.length / 1024).toFixed(0)} KB, ${hash}`);
}
